### ISSUE TITLE
game.c

### ISSUE THREAD

**Issue by sdk7327** [42rejects/c-sync-swim-december#10]
Description:
This is no small task, but your work is really going to shape this game. You're going to write game.c which will have all the questions and answers for our quiz. We'll need ten questions to make a complete game. They can be on any topic (and of any difficulty) that you'd like - you could even test the players' code knowledge! You'll need a way for the function to identify which answer is the right answer.  Every time the player answers correctly, you'll need to count it somehow, and then return the total correct answers to main the first time they miss a question, or when they've gotten all ten right.

Prototype: int game(void);

Requirements:
1) Clears the screen
2) Iterates through ten questions
3) Display each question with its four options (a, b, c, d)
4) Receive user input and checks it against the answer:
a) If valid response, but not correct, returns number of correct answers to that point
b) If correct, records track of number correct and moves on to next question
c) It all ten questions have been answered correctly, returns 10

**Comment by sdk7327** [comment]
Also, remember to comment! 42 doesn't like it, but your teammates will!

**Comment by iJUK3i** [comment]
ok I will take care of it!

**Comment by iJUK3i** [comment]
what should i do for if invalid response?

**Comment by iJUK3i** [comment]
nevermind its good

**Comment by roccaturi** [comment]
Notes from code review:
- Great use of structs for the question pool.
- Nice handling of extraneous user input via the cxq variable.
- Consider removing the endgame print statement (talk with Eugene for main.c and Danny for score.c) and returning int i to main.
- I liked the reporting of how many questions have been answered correctly. Could that be done in dollar value as a guide for how Danny will do it in score.c? 
- Great conversation about Twitch, Piscene, helping others, building out a shared library, and next projects!
- I will add the following libraries to the header (stdio.h, stdlib.h, unistd.h, and fcntl.h). Any others?
Thanks!

**Comment by iJUK3i** [comment]
That about covers it! You're welcome! It was nice to go over the project.  Everything we talked about worked out nicely, I added the $ and increments of 100,000 . couldn't think of anything else that was needed.
